# Generated by Django 5.1.4 on 2025-02-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_brand_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='titel',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Disable', 'Disable')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
