# Generated by Django 5.1.4 on 2025-02-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_remove_product_titel_product_status_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=100, null=True),
        ),
    ]
